### ISSUE TITLE
[Typescript] Export more types from the library

### ISSUE THREAD

**Issue by MikeyZat** [wert-io/widget-sc-signer#3]
Hi everyone,

While working on the integration, I was hoping that I can import some types from the library, e.g.
https://github.com/wert-io/widget-sc-signer/blob/master/index.d.ts#L1

I'd use them in my utility integration functions to **type expected input and possible signed output**. Currently I had to copy the types directly into my code to use them.

I know it's not a big deal but have you considered exporting them?

**Comment by onexsan** [comment]
Hello!

Apologies for the long reply and thank you for your suggestion, we'll consider adding typing one day.
